### ISSUE TITLE
Switch to Gradle?

### ISSUE THREAD

**Issue by brmeyer** [opendatakit/aggregate#106]
If I'm honest, I'm not a huge Gradle fan, at least not in most contexts.  But ODK Aggregate is one example where I think it may truly help.

For projects that simply need standard dependency management, standard composability, deployment/release management, and lightweight script/plugin use, Maven is still solid.  But where it Gradle shines is its ability to use Groovy scripts for dynamic and complex needs, such as Aggregate's GAE setup.  Rather than rely on a combo of Maven, Maven plugins (ugh), and Ant scripts, Gradle/Groovy has a pretty big advantage.

Other benefits:

- IDE support has come a **long** way in the last couple of years.
- Consistency with ODK's Android projects.
- Potential to replace the installer setup in its entirety, not requiring Maven to be first installed, etc.  Let the Gradle wrapper do its thing, keeping the entire setup self-contained and headless.  The end result would be the creation of deployable WAR, or completely scripting and automating a PaaS deployment.

Worries:

- It's improved lately, but Gradle can have slower build times than Maven.  But with the module separation suggested in https://github.com/opendatakit/aggregate/issues/105, this can mostly be mitigated for developers.
- Gradle scripts can be tricky to debug -- there seem to be 100 ways to shoot yourself in the foot.  But, arguably, Maven + Ant can be worse...

Curious to hear what everyone else things!  Maven vs Gradle vs whatever Google happens to be pushing seems to be rather divisive ;)

**Comment by lognaturel** [comment]
@arahayrabedian @kden @jovaee Are some of the people I can think of who were compiling Aggregate recently and might have some feedback.

I personally find the benefits compelling and the worries not all that worrisome so I'd be on board! I particularly like the idea that we'd have fewer tools to know across the different ODK projects.

**Comment by yanokwa** [comment]
@johnhbenetech It'd be good to get your feedback here too!

**Comment by kden** [comment]
So are we talking about continuing on Aggregate + ODK 1.0?  Will Aggregate continue to be relevant in 2.0?  Aggregate supports a lot of different technologies; if it continues on, I think it should be spun off into a GAE project, a relational DB project, and a shared code project.  Gradle is a natural for the GAE project; for a Tomcat/RDB project, it's more of a toss-up.

**Comment by lognaturel** [comment]
The short term goal is to make it easier to build Aggregate and get new releases ready as it transitions from being UW-supported to community-supported as @yanokwa outlined [here](https://forum.opendatakit.org/t/odk-aggregate-future-plans/9219/4). I presume that this will mostly be for the 1.0 suite since the nice work you and colleagues have done on [Hamster](https://github.com/benetech/odk-hamster) seems so well-suited for 2.0 but I'm not sure.

Good point about potentially splitting things up into multiple projects. @brmeyer also touched on that in #105.

**Comment by jbeorse** [comment]
Aggregate will not continue to be relevant in 2.0 in the long term, though we do still support it with reduced features. In 2.0 we are transitioning to a micro service architecture in which we are running Docker containers we are calling [sync endpoint containers](https://github.com/opendatakit/sync-endpoint-containers). You can see an example of how it might be set up [here](https://github.com/opendatakit/sync-endpoint-default-setup).

Inside the sync endpoint container is something descended from Aggregate that implements the 2.0 REST API (so it is a smooth transition from Aggregate to the sync endpoints), but it is NOT compatible with 1.0 and is NOT true fork of Aggregate that might contribute back. You can see that code [here](https://github.com/opendatakit/sync-endpoint). We have dropped GAE support and are working to shrink this repo and better suit it to relational DBs. This of course has nothing to do with what direction Aggregate might take, just an acknowledgement that supporting GAE and relational DBs together is difficult.

We have actually worked with Benetech to integrate some of their [Hamster](https://github.com/benetech/odk-hamster) work into the 2.0 setup. In particular we forked their UI [here](https://github.com/opendatakit/sync-endpoint-web-ui).

**Comment by jbeorse** [comment]
Unfortunately, I can't speak to a specific deprecation period for Aggregate from 2.0; that would require input from @wbrunette and possibly others. 

But I will try to clarify my previous post. Its not so much that we are replacing Aggregate as further decoupling the cloud component from the mobile component. We want to allow any implementation of the [2.0 sync protocol](https://github.com/opendatakit/opendatakit/wiki/ODK-2.0-Synchronization-API-(RESTful)) to function interchangeably with the 2.0 mobile tool suite. The latest release of Aggregate (1.4.15) is one such implementation of this API, and as such works with our latest release candidate and will work with the full release this month. We consider this protocol stable and don't anticipate any changes to it. Users wouldn't need to switch away from 1.4.15 until that protocol changed.

The sync endpoints are another implementation of the 2.0 sync protocol. As it stands now you could set up an Aggregate instance and a sync endpoint instance and switch back and forth from the phone without any problems. A sufficiently motivated user could also write their own implementation of the sync protocol and use that instead (and we anticipate this happening, though likely from forks of the sync endpoints). 

What I meant to say in the previous post was that the 2.0 development efforts at UW, particularly around new features, have been focused on the sync endpoints. For example the sync endpoints support group permissions via LDAP, which are NOT supported in Aggregate 1.4.15. Any users who want the associated features would need to switch to sync endpoints. The new UI that Benetech developed is also only included for the sync endpoints. Generally speaking sync endpoints are where future work will live without concern about trying to maintain feature parity with Aggregate. 

Also, I just spoke with @mitchellsundt and wanted to clarify one more point from my previous post regarding GAE. We have dropped support for Datastore, but you could still deploy a sync endpoint to Google's Cloud Platform by deploying the docker container the same way you might use that container on AWS or Azure. The key difference is that we're only supporting relational databases (in addition to the new UI, LDAP support, and removal of 1.0 code).

**Comment by wbrunette** [comment]
To answer @lognaturel and @jbeorse we envision people having a transition period from Aggregate to the Sync Endpoints. There are already users utilizing aggregate for the  2.0 sync protocols and we want to give them time to migrate. However, we do not expect to make any additional Aggregate changes to support the 2.0 sync protocols in Aggregate, as it already does not support the full functionality that the 2.0 sync endpoints do. Basically we are in sunset mode giving people a chance to migrate. The the Sync Endpoints are going to be released at the end of September and so a few months of sunset transition would make sense in IMHO.

**Comment by arahayrabedian** [comment]
Hi all, apologies on the late reply.

I'm really not a java person at the moment, so I can only give subjective/"how it felt" feedback here.

When I was trying to get Aggregate going, the biggest issue I had was figuring out enough of what was going on to get a build running in a way that would work with what I wanted to run (basically I was trying to get a development environment up).

I come from the world of interpreted language webapps/frameworks where selecting your backing store is (where possible) a runtime configuration param that simply hits up different backends (obviously I understand the java ecosystem is different), so it took me a while to get my head around the many possible compilations and the configurations they enable.

That said, I think maybe some clearer docs outlining the build/compile system would have been very helpful, I found it to be extremely intricately interrelated and often trying to do things I did not really need at that point in time. (I can't recall the exact situation at the moment)

Obviously I'm far less invested in this than developers who know what's going on, but my impression was that to run the application after even a minor modification involved a multi-minute build/compile.

I think with updated/modern documents with a single source of truth that it would make the onboarding/getting started process much smoother, I remember hearing this was already in the works so that's good :)

I hope that helps

**Comment by mitchellsundt** [comment]
w.r.t. the original question, switch to gradle?

This is a good idea for anyone restructuring this project.

Maven does not easily support unit tests, integration tests, and full-stack UI tests, all in one project build. 

That resulted in having the unit and integration tests in separate maven modules:
  mysql-unit-tests
  postgres-unit-tests
  sqlserver-unit-tests
  gae-unit-tests

(the unit tests can co-exist with the datastore integration tests within these modules because they can be viewed as degenerate cases of those integration tests where there is no interaction with the datastore).  These tests use a minimal SpringFramework context for the testing so that beans can be used to tie everything together. 

And then having the WAR builds and the UI full-stack tests (using selenium) in another set of projects:
  aggregate-gae
  aggregate-mysql
  aggregate-postgres
  aggregate-sqlserver

But there isn't no clean way to link the success of the former to the build of the later as a success criteria for the build. 

I haven't played around with gradle's J2EE build structures, so I don't know if there is an established way to handle this. On the down side, you might be rolling your own non-standard way of doing things. 

Ideally, the gradle build would clearly define and maintain these success criteria.

Another maven frustration, which may be fixed now, is that maven didn't support multiple outputs for a given module. 

The aggregate-src module should ideally have two different artifacts: (1) the jar of the built code and (2) a zip of the GWT compile content trees. 

As it is now, when the WAR is built, it needs to reference the exact same src tree in order to run the GWT compiler to generate the GWT content tree.  It would be nice if it could just reference the two artifacts of aggregate-src. I don't know if there is a standard artifact for GWT builds, so this might also require rolling your own stuff.

**Comment by ggalmazor** [comment]
Hi!

Just wanted to tell that I've created PR #112 with a proposal to migrate the project to Gradle. I've tried to document what's been done and would love to have your feedback and thoughts about it.

Thanks!

**Comment by yanokwa** [comment]
Fixed by #112.
