### ISSUE TITLE
Dupes or missing rows in repeat tables prevents users from listing and exporting submissions

### ISSUE THREAD

**Issue by ggalmazor** [opendatakit/aggregate#134]
There are two things that could happen inside a repeat: we have a missing row or we have a dupe row

Aggregate relies on the `_ORDINAL_NUMBER` field which should contain a sequence of ascending ints without holes and without dupes. If this sequence is wrong for 1 submission, we fail and the user can't see or export any submission at all

The safest thing to do is to show only the subset of repeat rows that match the expected sequence (1,2,3,4...) but this would lead to a rather difficult to predict behavior:
- If there is a hole as in `[1, 2, 4, 5, 6, 7]`: the user will only see rows `[1, 2]`
- If there is a dupe in the place of the hole as in `[1, 2, 2, 4, 5, 6, 7]`: the user will see `[1, 2(the first), 4, 5, 6, 7]`

The other option would be to show everything (dupes included). We would use `_ORDINAL_NUMBER` as an ordering parameter only and dupes/missing numbers wouldn't throw an error.

In any case, we wouldn't throw. Instead, we would leave a trace in the logs.

**Comment by ggalmazor** [comment]
@opendatakit-bot  label "needs discussion"

**Comment by yanokwa** [comment]
I haven't seen any examples of missing rows, but I've seen plenty of duplicate rows. 

To me, an ideal situation is showing/exporting everything when there is a missing row (`[1, 2, 4, 5, 6, 7]`) and showing/exporting the most recent duplicate when there is a duplicate (`[1, 2(the first), 4, 5, 6, 7]`). I say the most recent because historically, the [troubleshooting](https://github.com/opendatakit/opendatakit/wiki/Aggregate-AppEngine-Troubleshooting) instructions requested that you delete the earliest/latest, but I don't feel strongly about it.

Then, if possible, we note when we display the data that Aggregate has detected some table corruption and the use should click to see the corruption report.

**Comment by ggalmazor** [comment]
Alright! I can start working on that change :)
