### ISSUE TITLE
Set Up Test Summary on CircleCI builds

### ISSUE THREAD

**Issue by ggalmazor** [opendatakit/aggregate#188]
CircleCI runs the tests and fails if any test fails but we don't get a summary of what's going on with each build attempt.

#### Software and hardware versions 
N/A

#### Problem description
N/A

#### Steps to reproduce the problem
N/A

#### Expected behavior
N/A

#### Other information 
N/A

**Comment by yanokwa** [comment]
The tests don't run on CircleCI because there is no database. When you try to run the test, it'll run for 30+ minutes. I gave up after that. 

We'll have to first get a PostgreSQL DB running in CI. https://circleci.com/docs/2.0/postgres-config/#postgresql-circleci-configuration-example has a rough approach.

**Comment by ggalmazor** [comment]
@opendatakit-bot claim
