### ISSUE TITLE
Visualize submissions on Map issue.

### ISSUE THREAD

**Issue by kkrawczyk123** [opendatakit/aggregate#261]
#### Software and hardware versions 
Aggregate v1.6.x, Java v1.8.x, ... 

#### Problem description
I am not able to visualize submissions on the map on tomcat instance, the map is not loading at all:
![screenshot from 2018-06-21 12-43-12](https://user-images.githubusercontent.com/33342488/41714580-0e25698a-7551-11e8-8801-6e6ca58a1cb8.png)

I am able to visualize submissions on the map on GAE instance but with issues:
![a6](https://user-images.githubusercontent.com/33342488/41714613-2e6eabe8-7551-11e8-9c82-2948f2af70a8.png)

#### Steps to reproduce the problem
1. Try to Visualize submissions on geolocations on the map. 

#### Expected behavior
The map should open with no issues.

**Comment by kkrawczyk123** [comment]
This problem is connected to some settings on google cloud as today I am no longer able to reproduce this issue. @ggalmazor please confirm that is also not reproducible for you, and then I think that we can close it.

**Comment by ggalmazor** [comment]
Confirmed!

I tested it on GAE, local Tomcat and dev server. All working

**Comment by ggalmazor** [comment]
@kkrawczyk123 and I have found the cause of this intermittent problem.

- The google maps library is always loaded by the Aggregate main page
- The first time that happens, you haven't had the chance to set credentials yet, therefore, it's a library that will show the error and the watermarks about "only for dev purposes"
- The library gets cached on the browser
- After setting the credentials, you show again the map, but Aggregate doesn't reload the library
and you get the errors

Instead of that:
- If you close the window and open it again (in incognito mode) Aggregate gets the library again, this time with the API key, which makes the map work
- If you don't close the browser or manually clear history/caches it will keep on failing even on incognito mode
- logging out or refreshing the page doesn't guarantee that the browser will actually request a new library with the API key. It might take it from the cache. The only guaranteed method would be to clear history/cache or close the browser if you're on incognito mode

I guess now we should decide what to do:
- We can reload the page programmatically, but I'm not sure if that would guarantee that the library gets replaced with a new one with the API key
- We can add a notice on the prefs page telling users to remember they need to clear the browser cache to let changes take effect.

What do you think, @yanokwa, @lognaturel?

**Comment by ggalmazor** [comment]
I think this one can be closed, @kkrawczyk123 :)

**Comment by lognaturel** [comment]
Apologies, I missed this. Is it quick to do a test of programmatic page reload? It would be convenient if the user didn't have to perform any special action. But if it's a big thing to undertake or it doesn't work, a notice would certainly be fine.

**Comment by yanokwa** [comment]
Curious that the maps library is loaded by the main page and not the mapping page (which I believe is only available after you set credentials). Would moving that load to the map specific page solve this problem?

**Comment by ggalmazor** [comment]
I've tried programmatically reloading the page after a user sets an API key. That would force the reload of the script, avoiding the issue.

It turns out that the form is loaded inside an `<iframe>`, which makes it impossible for us to achieve this without some JS dark magic hacks that I'm not really inclined to add.

We could add a message like "If you have changed your Google Services API key, please, reload this page by hitting the refresh button".

**Comment by yanokwa** [comment]
Not sure I understand the ins and outs, but would this work?

1. If the API key isn't set, we add a notice on the mapping page asking them to set the API key.
2. Once we the API key status changes, we add a notice asking users to refresh the page.

**Comment by ggalmazor** [comment]
> If the API key isn't set, we add a notice on the mapping page asking them to set the API key.

If this happens, the map has some annoying watermarks and a dialog pops up with some error message (can't remember now, will update this comment with the exact message)

> Once we the API key status changes, we add a notice asking users to refresh the page.

OK, that's what I was proposing, seeing that programmatically reloading the page wasn't going to be an easy task.

**Comment by yanokwa** [comment]
I'm OK with what you are proposing as a solution.
