### ISSUE TITLE
Remove all ODK 2 code

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/aggregate#287]
I spoke to @wbrunette and it's safe to remove all the ODK 2 code and UI.

**Comment by lognaturel** [comment]
This is certainly a lot more convenient for maintenance but is it perhaps bad for users? From the forum, it seems most users of Tables/Survey/etc use Aggregate and so this means they wouldn't get security updates, lib updates, etc.

**Comment by yanokwa** [comment]
Fair point, but currently, we don't test against ODK 2 at all and that's also bad for users. And I'm pretty sure the ODK 2 also doesn't test their changes against Aggregate. The only version the ODK 2 docs guarantee as functional is v1.4.15.

@wbrunette are there a lot of Tables/Survey users who are using Aggregate?

**Comment by wbrunette** [comment]
Sorry, for the delayed response. 
Yes, there are people using Aggregate for ODK 2 because they do not need all the features offered by Sync-Endpoint. However, the divergence of code will continue and will likely lead to future problems so I support removing ODK 2 code from Aggregate. 

@lognaturel suggestion about getting the security updates for the people already on Aggregate is a good one. Therefore, while preparing the Survey/Tables/Services release in August (version 2.1), I will test against the latest version of Aggregate and see if the basic functionality still works. After blessing another release (besides version 1.4.15) I suggest we sunset Aggregate's ODK 2 support and remove it from Aggregate since the code will continue to diverge.

**Comment by poVoq** [comment]
For the time being Sync-endpoint is not very convenient to self-host (mainly due to OpenLDAP requirement) and also lacks a lot of functionality offered by Aggregate. I am also unsure why you would want to further diverge the two branches of ODK instead of trying to integrate them better (as I guess somewhat offered by Aggregate right now).
