### ISSUE TITLE
Re-visit need for IntelliJ IDEA

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/aggregate#302]
According to JetBrains...

> Please note that some of the rules of our [Open Source Support Program](https://www.jetbrains.com/buy/opensource/) have changed. Most importantly, if there is a commercial company or an organization that sponsors your OS project, i.e. if the developers are employed to work on the OS project, we will no longer be able to provide you with free licenses.

@ggalmazor Can you clarify IntelliJ Community Edition is sufficient for contributing to Aggregate? https://www.jetbrains.com/idea/features/editions_comparison_matrix.html

**Comment by ggalmazor** [comment]
I don't think anything has changed on this matter. I checked last year when I started with ODK and I'd swear the part of the license conditions you've quoted hasn't really changed since (maybe I'm missing something).

I can confirm that the Community edition is sufficient for contributing to Aggregate. All our build and tooling processes are based on Gradle and this means that we are not using any of the IDE's features to do things such as building the WAR file, running a dev server, or running the tests. Gradle is supported by the Community edition.

The Ultimate version comes with interesting stuff, though: Google App Engine, GWT, Tomcat, among others. These features can be useful for specific parts of the workflow, but **they are not required to work in Aggregate**. I don't use any of these in my day-to-day, but I've used the GWT support to run the client in superdebug mode and it is remarkably faster than relaunching the dev server after I change some page.

**Comment by yanokwa** [comment]
Perfect. Thanks for clarifying, @ggalmazor.

CC'ng @wbrunette so he sees this.

**Comment by wbrunette** [comment]
Thanks for the cc. Great to know that we have improved the command line with Gradle since the first migration. Thanks for clarifying so we know we are good.

I think comments like this tie back to this though:
https://github.com/opendatakit/aggregate/issues/299#issuecomment-413564318
and
https://github.com/opendatakit/aggregate/issues/299#issuecomment-413515152

HOWEVER, I am not advocating for prioritizing any changes at this time. A system that works independently is enough, there are always nice to haves and we have limited resources :)
