### ISSUE TITLE
aggregate-config only works if ports are 80/433

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/aggregate#312]
#### Software and hardware versions 
Aggregate v1.6.1 VM

#### Problem description
If you use run aggregate-config and use a port other than 80 or 443, you will not be able to change passwords. I believe this is the root issue at https://forum.opendatakit.org/t/unable-to-add-or-modify-password-to-users/12624.

#### Steps to reproduce the problem
* Switch the VM to bridged mode and get an IP (e.g., 192.168.7.61)
* Run the FQDN command `aggregate-config --fqdn 192.168.7.61 --http-port 8080 --https-port 8443`
* Try to connect to the server at 192.168.7.61:8080, it won't work, but 192.168.7.61:80 will. But then you get lots of weird behavior when trying to change the password.

#### Expected behavior
I expect that connecting via 8080 will work. 

#### Other information 
I think the problem here is that Tomcat (server.xml) is listening at port 80/443 and aggregate-config does not change that port, but it should.

**Comment by ggalmazor** [comment]
Thanks for all the detail. It should be easy to make the aggregate-config tool to change the server as well. I believe that we can reuse some part of the conf script for the docker images.

**Comment by ggalmazor** [comment]
I think this issue requires a little bit more discussion.

The VM’s networking is based on NAT networking. This works this way:
- Tomcat serves at 80 and 443
- NAT redirects 80 to 10080 and 443 to 10443
- aggregate-config changes Aggregate’s conf files and it’s meant to be used with the NAT’ed ports

Using bridged networking would require changing tomcat’s conf, which would break the NAT setup because it relies on Tomcat using 80/443.

If we want to support bridged networks, we could add a new `--net-mode nat|bridge` argument to the `aggregate-config` tool:
- The nat mode would overwrite Tomcat’s conf to use 80/443 and set Aggregate's conf to the ports from user input.
- The bridge mode would use the ports from user input both for Tomcat's and Aggregate's conf files.
